### ISSUE TITLE
Unable to resolve org.springframework:spring-jdbc:5.0.6.RELEASR

### ISSUE THREAD

**Issue by ChildrenGreens** [spring-guides/gs-accessing-data-mysql#13]
In the "Accessing Relational Data using JDBC with Spring" example:

I imported the project and found the following problem.

Unable to resolve org.springframework:spring-jdbc:5.0.6.RELEASR
<img width="1676" alt="2018-05-21 16 51 12" src="https://user-images.githubusercontent.com/16026959/40301131-ba7f6704-5d1d-11e8-9405-99c574844ba6.png">
How to solve this warning?

**Comment by dsyer** [comment]
Works for me. Maybe you have a bad jar?

**Comment by ChildrenGreens** [comment]
@dsyer 
Thank you, I solved it.

**Comment by allentofight** [comment]
> @dsyer
> Thank you, I solved it.

how to resolve it , I meet the same problem
