### ISSUE TITLE
How to use findByNeer in Mysql 5.7 + ？

### ISSUE THREAD

**Issue by chenlingmin** [spring-guides/gs-accessing-data-mysql#15]

**Comment by dsyer** [comment]
What's "neer"? What do you mean exactly? Is it anything to do with MySQL?

**Comment by chenlingmin** [comment]
Sorry. Spelling mistakes, It's Near。
For example:
- Nearby hospital
- Nearby companies

**Comment by dsyer** [comment]
Is that a MySQL feature? Seems like a concern you would have to implement yourself in Java. I'm not really sure what you are asking. This guide is only about using MySQL, as opposed to an embedded database. It doesn't cover specific features of MySQL, and it doesn't cover specific features in Java APIs that use the database.

**Comment by chenlingmin** [comment]
😂 Sorry, My English is poor.

I want to know how to use `spring-data-commons`  and `spring-data-jpa` with Mysql query nearBy ***. like this.

`Page<Store> findByAddressLocationNear( @Param("location") Point location, @Param("distance") Distance distance, Pageable pageable)`

**Comment by dsyer** [comment]
I’m not aware if MySQL has such a feature. It’s out of the scope of this guide though. Please take usage questions to StackOverflow.
