### ISSUE TITLE
MySQLSyntaxErrorException: You have an error in your SQL syntax;

### ISSUE THREAD

**Issue by nickkulese** [spring-guides/gs-accessing-data-mysql#19]
Can not run it :(  
Getting error: 
MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '??' at line 1

I'm doing the same as it's written in ReadMe. 
Using MySQL 8.0.15

What could be wrong here?

**Comment by dsyer** [comment]
You might need to be a little bit more explicit with your description of what you did.

**Comment by nickkulese** [comment]
Alright, so I executed these commands in mysql:

mysql> create database db_example; -- Create the new database
mysql> create user 'springuser'@'%' identified by 'ThePassword'; -- Creates the user
mysql> grant all on db_example.* to 'springuser'@'%'; -- Gives all the privileges to the new user on the newly created database

Then just tried to run the complete one, using ItelliJ Idea.

**Comment by dsyer** [comment]
So what went wrong where? What did you do when you “tried to run the complete one?” Was there a stack trace with that exception or an error message?
