### ISSUE TITLE
NoSuchBeanDefinitionException: No qualifying bean of type 'hello.UserRepository' available: expected at least 1 bean which qualifies as autowire candidate.

### ISSUE THREAD

**Issue by wilixx** [spring-guides/gs-accessing-data-mysql#24]
NoSuchBeanDefinitionException: No qualifying bean of type 'hello.UserRepository' available: expected at least 1 bean which qualifies as autowire candidate.

I am dying with this issue for a week. Can anyone help me? I think I could  never use spring boot afterwards.....

**Comment by dsyer** [comment]
Are you running the code from the “complete” sample? Works for me.

**Comment by jo2** [comment]
@wilixx if this is still current, do you have an example project? Only having the error message it is hard to help.
