### ISSUE TITLE
Unable to start application

### ISSUE THREAD

**Issue by Hirenvaghasiya** [spring-guides/gs-accessing-data-mysql#3]
Run Logs attached.

[RunLogs.txt](https://github.com/spring-guides/gs-accessing-data-mysql/files/981351/RunLogs.txt)

**Comment by dsyer** [comment]
It's  pretty clear form the last game that you have some bad jar files (downloaded when not authenticated at a wifi hub maybe?). You can just clear the maven cache completely, or delete the files that are bad and refresh them.
