### ISSUE TITLE
Timezone Problem 

### ISSUE THREAD

**Issue by ieyring** [spring-guides/gs-accessing-data-mysql#37]
try to run the Application gives:

java.sql.SQLException: The server time zone value 'Mitteleuropõische Sommerzeit' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.

**Comment by lengyyy** [comment]
same issue, solved by change the application.properties:
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example?useLegacyDatetimeCode=false&serverTimezone=UTC

**Comment by ieyring** [comment]
Yeah, in my Case solved with: 
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Berlin
