### ISSUE TITLE
Path not found

### ISSUE THREAD

**Issue by sabrinaslattery** [spring-guides/gs-accessing-data-mysql#42]
I'm having an issue with Java EE on Eclipse not finding the paths mapped in the MainController.java file.

<img width="808" alt="Screen Shot 2020-12-05 at 3 20 51 PM" src="https://user-images.githubusercontent.com/70298531/101267434-79a6a900-370d-11eb-82a1-8f313fd55a86.png">

Any suggestions?

**Comment by dsyer** [comment]
Are you following the same guide? I see “JPA” in the console, but this is the mysql guide.

**Comment by AAdewunmi** [comment]
@sabrinaslattery 
A good place to start debugging is to understand the error message:

**The HTTP 404 Not Found response status code indicates that the server cannot find the requested resource. Links that lead to a 404 page are often called broken or dead links and can be subject to link rot.**

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404?retiredLocale=de

I suggest you work back though your code by first checking:

1. @RequestMapping(path="/demo")
2. @PostMapping(path="/add")

Then make sure your code is the same as the guide's.

Good luck

😎
