### ISSUE TITLE
Incorrect MySQL driver

### ISSUE THREAD

**Issue by Igor-Polatajko** [spring-guides/gs-accessing-data-mysql#50]
The project is using ["mysql-connector-java" as MySQL driver](https://github.com/spring-guides/gs-accessing-data-mysql/blob/main/complete/pom.xml#L31), but according to the [documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/dependency-versions.html) "mysql.mysql-connector-java" is not provided as part of the BOM, so "com.mysql.mysql-connector-j" should be used instead.

**Comment by vincenthsin** [comment]
Hi @Igor-Polatajko , both of them are included. 

 <dependency>
        <groupId>com.mysql</groupId>
        <artifactId>mysql-connector-j</artifactId>
        <version>${mysql.version}</version>
        <exclusions>
          <exclusion>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
          </exclusion>
        </exclusions>
      </dependency>
      <dependency>
        <groupId>mysql</groupId>
        <artifactId>mysql-connector-java</artifactId>
        <version>${mysql.version}</version>
        <exclusions>
          <exclusion>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
          </exclusion>
        </exclusions>
      </dependency>
