### ISSUE TITLE
Missing MySQL dependency

### ISSUE THREAD

**Issue by benstadlbauer** [spring-guides/gs-accessing-data-mysql#57]
This issue is more of a question/clarification.

### Why is the MySQL-driver not listed as dependency in the `complete` project?

If one completes the guide [Accessing data with MySQL](https://spring.io/guides/gs/accessing-data-mysql/) then there is no problem (as @Buzzardo mentioned [here](https://github.com/spring-guides/gs-accessing-data-mysql/pull/53#issuecomment-1769262487)), because the guide states to include the MySQL Driver (see [Starting with Spring Initializr](https://spring.io/guides/gs/accessing-data-mysql/#scratch)).

But if one directly downloads this git repository and tries to run the `complete` project, it won't work. There are already two issues regarding this very problem: #53 , #52 . 

Thank you!

**Comment by Buzzardo** [comment]
I suppose we could add a note at the top to state that MySQL must be available. I'll make this one available to the community, as we are trying to encourage more community engagement with the guide repositories.

**Comment by j0holo** [comment]
I have a similar problem. The documentation is no longer up-to-date.

In `build.gradle` I need to add the following `dependency`: `runtimeOnly 'com.mysql:mysql-connector-j'`

And in `application.properties` the `spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver` setting is no longer required to start the server.

Could I create a pull request for these changes? Or is there something I'm missing?

**Comment by Buzzardo** [comment]
Feel free to create a pull request. Thanks.

**Comment by robertmcnees** [comment]
Fixed with #58
