### ISSUE TITLE
Remove unused CI files

### ISSUE THREAD

**Issue by robertmcnees** [spring-guides/gs-accessing-data-mysql#62]
The file `test/run.sh` is no longer required. This file and the `test` directory can be deleted.

The file was originally used for Jenkins CI. Now that this project has been converted to GitHub Actions, this file can be removed.

**Comment by gyrnjs12** [comment]
Can I work on this issue? kindly assign it to me!

**Comment by robertmcnees** [comment]
Thanks for the PR! I merged in the PR so I will close this issue.

(in spring-guides, and Spring projects in general, we usually don't assign people to issues but rather accept the first PR that comes through for a given issue)
